### ISSUE TITLE
https://github.com/dalequi/meteor-meteoric-boilerplate 的css问题

### ISSUE THREAD

**Issue by seanjsong** [maodouio/meteor-master-classes#3]
client/stylesheets/app.scss中有

@import '.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/ionic';
@import '.meteor/local/build/programs/server/assets/packages/meteoric_ionicons-sass/ionicons';

而那两个目录下实际能找到的文件只有：

.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/_ionic.scss
.meteor/local/build/programs/server/assets/packages/meteoric_ionicons-sass/_ionicons.scss

问题：
1. 这是SCSS的特殊语法么？实际引用的就是_ionic.scss和_ionicons.scss这两个文件？
2. 在源代码中还要去引用build目录下的文件，也太不雅了吧，是用ionic必须这么做吗？有没有更好的办法？

**Comment by limingth** [comment]
@seanjsong  确实不雅，不过暂时似乎没有更好的办法。

参考阅读： https://github.com/meteoric/ionic-sass

NOTE: Due to a current limitation of the Meteor packaging system, the above path may not exist the first time you run your Meteor app after installing this package. This will cause an error saying the file to import was not found. This may also occur if you run meteor reset. Restarting your app should fix this problem. See meteor/meteor#2606 and meteor/meteor#2796 for more info.

**Comment by kevingzhang** [comment]
此问题应该是导致需要运行 meteor 两次的原因. 的确不雅. 是一种 hack. 估计以后会改变. 
我个人更加喜欢 less 超过 sass
